// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxHI4pDKY-4CsmmALF4GVdwtZOxYAZkHk',
    appId: '1:267381428578:web:d7e3fc9294a5423e2c5c3b',
    messagingSenderId: '267381428578',
    projectId: 'ramaz-go',
    authDomain: 'ramaz-go.firebaseapp.com',
    databaseURL: 'https://ramaz-go.firebaseio.com',
    storageBucket: 'ramaz-go.appspot.com',
    measurementId: 'G-STL2M6CLDT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtgjKhWYA9iwNNdPJB8fdYAFGg8rKUhBk',
    appId: '1:267381428578:android:8be588f5967f914f',
    messagingSenderId: '267381428578',
    projectId: 'ramaz-go',
    databaseURL: 'https://ramaz-go.firebaseio.com',
    storageBucket: 'ramaz-go.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6rEaYZeHcxeW5ZU2i_YQCYmwgwx8f07s',
    appId: '1:267381428578:ios:196e12b81f2bcae22c5c3b',
    messagingSenderId: '267381428578',
    projectId: 'ramaz-go',
    databaseURL: 'https://ramaz-go.firebaseio.com',
    storageBucket: 'ramaz-go.appspot.com',
    androidClientId: '267381428578-02uu4a03um3dfo10oq6akse1f0dlkc84.apps.googleusercontent.com',
    iosClientId: '267381428578-7dem1o3hm0qsb92lpcst43cmj95t4mv0.apps.googleusercontent.com',
    iosBundleId: 'com.ramaz.coding.ramlife',
  );
}
